Repository Team-Neoul/Neoul_Dotoring-BE, pull requests merged in 2023-09, with the labels that each got.

#25 [Kevin] 쪽지함 Spec 수정
  build/generated/'querydsl'/generated/com/theZ/dotoring/app/room/mapper/RoomMapperImpl.java
  src/main/java/com/theZ/dotoring/app/room/mapper/RoomMapper.java
Labels: bug

#26 [Kevin] Letter, Room 클래스, 메서드 주석 작성
  src/main/java/com/theZ/dotoring/app/letter/controller/LetterFromMentiController.java
  src/main/java/com/theZ/dotoring/app/letter/controller/LetterFromMentoController.java
  src/main/java/com/theZ/dotoring/app/letter/domain/Letter.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/CreateLetterByMentiHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/CreateMentiLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/GetMentiLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/menti/GetRoomByMentiHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/CreateLetterByMentoHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/CreateMentoLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/GetMentoLetterByRoomHandler.java
  src/main/java/com/theZ/dotoring/app/letter/handler/mento/GetRoomByMentoHandler.java
  src/main/java/com/theZ/dotoring/app/letter/mapper/LetterMapper.java
  src/main/java/com/theZ/dotoring/app/letter/repository/LetterRepository.java
  src/main/java/com/theZ/dotoring/app/letter/service/LetterMentiService.java
  src/main/java/com/theZ/dotoring/app/letter/service/LetterMentoService.java
  src/main/java/com/theZ/dotoring/app/room/domain/Room.java
  src/main/java/com/theZ/dotoring/app/room/mapper/RoomMapper.java
  src/main/java/com/theZ/dotoring/app/room/repository/RoomRepository.java
  src/main/java/com/theZ/dotoring/app/room/service/RoomService.java
Labels: documentation

#30 [Sonny] Mento, Menti Mock Data 추가2
  .gradle/7.6.1/executionHistory/executionHistory.bin
  .gradle/7.6.1/executionHistory/executionHistory.lock
  .gradle/7.6.1/fileHashes/fileHashes.bin
  .gradle/7.6.1/fileHashes/fileHashes.lock
  .gradle/7.6.1/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/classes/java/main/com/theZ/dotoring/common/DataInit$InitService.class
  build/classes/java/main/com/theZ/dotoring/common/DataInit.class
  build/tmp/compileJava/compileTransaction/stash-dir/DataInit$InitService.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/DataInit.class.uniqueId1
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/theZ/dotoring/common/DataInit.java
Labels: enhancement
