Repository Team-Neoul/Neoul_Dotoring-BE, pull requests merged in 2023-11, with the labels that each got.

#61 Test 데이터 넣기
  src/main/java/com/theZ/dotoring/app/menti/model/Menti.java
  src/main/java/com/theZ/dotoring/app/mento/model/Mento.java
  src/main/java/com/theZ/dotoring/common/DataInit.java
  src/main/java/com/theZ/dotoring/common/Major.java
  src/main/resources/application-local.yml
  src/main/resources/db/init.sql
Labels: enhancement

#62 Mock Data 수정
  src/main/resources/db/init.sql
  src/test/java/com/theZ/dotoring/app/menti/controller/MentiControllerTest.java
  src/test/java/com/theZ/dotoring/app/mento/controller/MentoControllerTest.java
Labels: enhancement

#63 init.sql yml 파일에 추가
  src/main/resources/application-local.yml
Labels: enhancement

#67 CORS 설정 적용
  src/main/java/com/theZ/dotoring/config/WebSecurityConfig.java
  src/test/java/com/theZ/dotoring/app/auth/controller/AuthControllerTest.java
Labels: documentation

#74 멘토, 멘티 전체 조회 기능 수정 및 CI 워크플로우 수정
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/com/theZ/dotoring/DotoringApplication.java
  src/main/java/com/theZ/dotoring/app/desiredField/repository/QueryDesiredFieldRepository.java
  src/main/java/com/theZ/dotoring/app/menti/service/MentiService.java
  src/main/java/com/theZ/dotoring/app/mento/service/MentoService.java
  src/main/java/com/theZ/dotoring/config/EnvConfig.java
  src/main/resources/application-test.yml
  src/main/resources/db/init.sql
  src/main/resources/env/env.yaml
  src/test/java/com/theZ/dotoring/DotoringApplicationTests.java
  src/test/java/com/theZ/dotoring/app/auth/controller/AuthControllerTest.java
  src/test/java/com/theZ/dotoring/app/menti/controller/MentiControllerTest.java
  src/test/java/com/theZ/dotoring/app/mento/controller/MentoControllerTest.java
Labels: bug, enhancement

#83 기존 채팅 코드들 현 버젼에 맞춰 고도화
  src/main/java/com/theZ/dotoring/app/chat/controller/MessageController.java
  src/main/java/com/theZ/dotoring/app/chat/dto/ChatMessageResponsePageDTO.java
  src/main/java/com/theZ/dotoring/app/chat/entity/ChatMessage.java
  src/main/java/com/theZ/dotoring/app/chat/repository/MessageRepository.java
  src/main/java/com/theZ/dotoring/app/chatRoom/controller/ChatRoomController.java
  src/main/java/com/theZ/dotoring/app/chatRoom/entity/ChatRoom.java
  src/main/java/com/theZ/dotoring/app/chatRoom/repository/ChatRoomRespository.java
  src/main/java/com/theZ/dotoring/app/chatRoom/service/ChatRoomService.java
  src/main/java/com/theZ/dotoring/app/memberAccount/repository/MemberAccountRepository.java
  src/main/java/com/theZ/dotoring/app/memberAccount/service/MemberAccountService.java
  src/main/java/com/theZ/dotoring/app/menti/repository/MentiRepository.java
  src/main/java/com/theZ/dotoring/app/mento/repository/MentoRepository.java
Labels: enhancement

#88 FcmConfig 주석처리
  src/main/java/com/theZ/dotoring/config/FCMConfig.java
  src/main/resources/env/env.yaml
Labels: bug

#90 CloudType 배포 환경 구축 및 배포
  .gradle/7.6.1/executionHistory/executionHistory.bin
  .gradle/7.6.1/executionHistory/executionHistory.lock
  .gradle/7.6.1/fileHashes/fileHashes.bin
  .gradle/7.6.1/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules/dotoring.main.iml
  .idea/workspace.xml
  build/generated/sources/annotationProcessor/java/main/com/theZ/dotoring/app/letter/mapper/LetterMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/theZ/dotoring/app/room/mapper/RoomMapperImpl.java
  build/resources/main/application.properties
  build/tmp/compileJava/previous-compilation-data.bin
  commonSW.md
  src/main/java/com/theZ/dotoring/common/ApiResponse.java
  src/main/java/com/theZ/dotoring/common/ApiResponseGenerator.java
  src/main/java/com/theZ/dotoring/exception/GlobalExceptionHandler.java
  src/main/resources/application.properties
Labels: enhancement

#92 마이 페이지 관련 기능변경으로 인한 수정 및 테스트
  src/main/java/com/theZ/dotoring/app/field/service/FieldService.java
  src/main/java/com/theZ/dotoring/app/major/service/MajorService.java
  src/main/java/com/theZ/dotoring/app/memberAccount/controller/MemberAccountController.java
  src/main/java/com/theZ/dotoring/app/menti/controller/MentiController.java
  src/main/java/com/theZ/dotoring/app/menti/dto/FindAllMentiRespDTO.java
  src/main/java/com/theZ/dotoring/app/menti/dto/FindMentiByIdRespDTO.java
  src/main/java/com/theZ/dotoring/app/menti/dto/FindMyMentiRespDTO.java
  src/main/java/com/theZ/dotoring/app/menti/dto/SaveMentiRqDTO.java
  src/main/java/com/theZ/dotoring/app/menti/dto/UpdateMentiRqDTO.java
  src/main/java/com/theZ/dotoring/app/menti/dto/UpdateMentiStatusRqDTO.java
  src/main/java/com/theZ/dotoring/app/menti/dto/UpdatePreferredMentoringRqDTO.java
  src/main/java/com/theZ/dotoring/app/menti/handler/UpdateMentiHandler.java
  src/main/java/com/theZ/dotoring/app/menti/mapper/MentiMapper.java
  src/main/java/com/theZ/dotoring/app/menti/model/Menti.java
  src/main/java/com/theZ/dotoring/app/menti/model/TempMenti.java
  src/main/java/com/theZ/dotoring/app/menti/repository/TempMentiRepository.java
  src/main/java/com/theZ/dotoring/app/menti/service/MentiService.java
  src/main/java/com/theZ/dotoring/app/menti/service/TempMentiService.java
  src/main/java/com/theZ/dotoring/app/mento/controller/MentoController.java
  src/main/java/com/theZ/dotoring/app/mento/dto/FindAllMentoRespDTO.java
  src/main/java/com/theZ/dotoring/app/mento/dto/FindMentoByIdRespDTO.java
  src/main/java/com/theZ/dotoring/app/mento/dto/FindMyMentoRespDTO.java
  src/main/java/com/theZ/dotoring/app/mento/dto/SaveMentoRqDTO.java
  src/main/java/com/theZ/dotoring/app/mento/dto/UpdateMentoRqDTO.java
  src/main/java/com/theZ/dotoring/app/mento/dto/UpdateMentoStatusRqDTO.java
  src/main/java/com/theZ/dotoring/app/mento/dto/UpdateMentoringSystemRqDTO.java
  src/main/java/com/theZ/dotoring/app/mento/dto/UpdateTagsRqDTO.java
  src/main/java/com/theZ/dotoring/app/mento/handler/UpdateMentoHandler.java
  src/main/java/com/theZ/dotoring/app/mento/mapper/MentoMapper.java
  src/main/java/com/theZ/dotoring/app/mento/model/Mento.java
  src/main/java/com/theZ/dotoring/app/mento/model/TempMento.java
  src/main/java/com/theZ/dotoring/app/mento/repository/TempMentoRepository.java
  src/main/java/com/theZ/dotoring/app/mento/service/MentoService.java
  src/main/java/com/theZ/dotoring/app/mento/service/TempMentoService.java
  src/main/java/com/theZ/dotoring/common/S3Connector.java
  src/main/java/com/theZ/dotoring/common/StringListUtils.java
  src/main/java/com/theZ/dotoring/common/URLService.java
  src/main/java/com/theZ/dotoring/config/WebSecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/db/init.sql
  src/test/java/com/theZ/dotoring/app/menti/controller/MentiControllerTest.java
  src/test/java/com/theZ/dotoring/app/mento/controller/MentoControllerTest.java
  src/test/java/com/theZ/dotoring/common/StringListUtilsTest.java
Labels: enhancement

#93 충돌 문제 해결
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/modules/dotoring.main.iml
  .idea/workspace.xml
  build/generated/sources/annotationProcessor/java/main/com/theZ/dotoring/app/letter/mapper/LetterMapperImpl.java
  build/generated/sources/annotationProcessor/java/main/com/theZ/dotoring/app/room/mapper/RoomMapperImpl.java
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/theZ/dotoring/exception/GlobalExceptionHandler.java
Labels: bug

#95 queryDSL 빌드 오류 해결
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .idea/misc.xml
  .idea/modules/dotoring.main.iml
  .idea/workspace.xml
  build.gradle
  src/main/resources/application-cloud.yml
Labels: bug
